const Movies=[
    {
        id:1,
        image:"https://rukminim2.flixcart.com/image/612/612/xif0q/movie/4/f/r/2009-dvd-eagle-hindi-tarzan-the-wonder-car-original-imahfdpjpqg85j5d.jpeg?q=70",
        title:"Tarzan the wonder car",
        language:"hindi",
        cost:"250"
    },
    {
        id:2,
        image:"https://rukminim2.flixcart.com/image/612/612/xif0q/movie/e/t/s/2011-dvd-eagle-hindi-pratiggya-original-imagsy5gzggp4qyg.jpeg?q=70",
        title:"pratiggya",
        language:"hindi",
        cost:"250"
    },
    {
        id:3,
        image:"https://rukminim2.flixcart.com/image/612/612/jc6jl3k0/movie/h/h/d/1972-blu-ray-eagle-hindi-bawarchi-blu-ray-original-imaffc889xx7zm4n.jpeg?q=70",
        title:"Bawarchi",
        language:"hindi",
        cost:"250"
    },
    {
        id:4,
        image:"https://rukminim2.flixcart.com/image/612/612/l45xea80/movie/v/m/b/1696-dvd-captain-india-hindi-pyar-hi-pyar-original-imagf4b6nyjrsj7x.jpeg?q=70",
        title:"pyar hi pyar",
        language:"hindi",
        cost:"250"
    },
    {
        id:5,
        image:"https://rukminim2.flixcart.com/image/612/612/xif0q/movie/u/l/h/1948-dvd-eagle-hindi-mela-original-imagj578mfj4njyy.jpeg?q=70",
        title:"mela",
        language:"hindi",
        cost:"250"
    },
    {
        id:6,
        image:"https://rukminim2.flixcart.com/image/612/612/xif0q/movie/7/u/g/2013-blu-ray-eagle-hindi-anand-original-imagmhmzyz9kqtmt.jpeg?q=70",
        title:"anand",
        language:"hindi",
        cost:"250"
    },
    {
        id:7,
        image:"https://rukminim2.flixcart.com/image/612/612/xif0q/movie/u/l/h/1948-dvd-eagle-hindi-mela-original-imagj578mfj4njyy.jpeg?q=70",
        title:"",
        language:"hindi",
        cost:"250"
    },
    {
        id:8,
        image:"https://rukminim2.flixcart.com/image/612/612/xif0q/movie/u/l/h/1948-dvd-eagle-hindi-mela-original-imagj578mfj4njyy.jpeg?q=70",
        title:"",
        language:"hindi",
        cost:"250"
    },
    {
        id:9,
        image:"https://rukminim2.flixcart.com/image/612/612/xif0q/movie/u/l/h/1948-dvd-eagle-hindi-mela-original-imagj578mfj4njyy.jpeg?q=70",
        title:"",
        language:"hindi",
        cost:"250"
    },
    {
        id:10,
        image:"https://rukminim2.flixcart.com/image/612/612/xif0q/movie/u/l/h/1948-dvd-eagle-hindi-mela-original-imagj578mfj4njyy.jpeg?q=70",
        title:"",
        language:"hindi",
        cost:"250"
    }
]
export default Movies;